name: "local-aws"
services:
  local_s3:
    image: localstack/localstack:s3-latest
    container_name: "local_s3_main"
    env_file: "./.env"
    pull_policy: always
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - DEBUG=0
      - PERSISTENCE=1
      - SERVICES=s3
    networks:
      - local_aws_network
    volumes:
      - local_aws_s3_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  local_aws_s3_data:
    name: local_aws_s3_data
networks:
  local_aws_network:
    name: local_aws_network
    driver: bridge
