name: "local-aws"
services:
  local_s3:
    image: gresau/localstack-persist:4.12.0
    container_name: "local_s3_main"
    env_file: "./.env"
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - SERVICES=s3
    networks:
      - local_aws_network
    volumes:
      - local_aws_s3_data:/persisted-data
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  local_aws_s3_data:
    name: local_aws_s3_data
networks:
  local_aws_network:
    name: local_aws_network
    driver: bridge
