name: "local-aws"
services:
  local-s3:
    image: localstack/localstack:s3-latest
    container_name: "local-s3-main"
    env_file: "./.env"
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=s3
      - DEBUG=0
      - DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - HOSTNAME_EXTERNAL=local-s3-main
      - DATA_DIR=/var/lib/localstack/data
    networks:
      - local_aws_network
    volumes:
      - local_aws_s3_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  local_aws_s3_data:
    name: local_aws_s3_data
networks:
  local_aws_network:
    name: local_aws_network
    driver: bridge
