# Creates development database

# .postgres.env schema:
# POSTGRES_PASSWORD

name: "sql"
services:
  postgres:
    image: "postgres:17-alpine"
    container_name: "postgres_dev"
    env_file: "./.env"
    ports:
      - "5432:5432"
    networks:
      - postgres_dev_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: "Europe/Bratislava"
      PGTZ: "Europe/Bratislava"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres_data:
    name: postgres_dev_data
networks:
  postgres_dev_network:
    name: postgres_dev_network
    driver: bridge
